---
- name: APT - Install Build dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - "build-essential" 
    - "checkinstall"

- name: APT - Install other dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - "libreadline-gplv2-dev"
    - "libncursesw5-dev"
    - "libssl-dev"
    - "libsqlite3-dev"
    - "tk-dev" 
    - "libgdbm-dev"
    - "libc6-dev" 
    - "libbz2-dev"

